db:
  build: ./vendor/datahog/postgres
  ports:
    - "6543:5432"
  volumes_from:
    - data
  environment:
    - DATAHOG_PG_USER=databacon
    - DATAHOG_PG_DB=databacon

data:
  image: postgres
  container_name: data
  volumes:
    - /var/li/postgresql/9.3/main

databacon:
  build: ./databacon
  links:
    - db
  volumes:
    - ./databacon:/src
    - ./vendor/datahog:/datahog
  command: /bin/sh -c 'sleep 999999999999999999999'
   