db:
  build: ./postgres
  ports:
    - "6543:5432"
  volumes_from:
    - data

data:
  image: postgres
  container_name: data
  volumes:
    - /var/li/postgresql/9.3/main

databacon:
  build: ./databacon
  links:
    - db
  volumes:
    - ./databacon:/src
    - ./datahog:/datahog
    - ./mummy:/mummy
  command: /bin/sh -c 'sleep 999999999999999999999'
   