db:
  build: ./postgres
  ports:
    - "6543:5432"
  volumes_from:
    - data

data:
  image: postgres
  volumes:
    - /var/li/postgresql/9.3/main

databacon:
  build: ./databacon
  links:
    - db
  volumes:
    - ./databacon:/src
  command: "/bin/bash -c 'sleep 99999999999'"
   